export type NotoErrorCode =
  | 'BAD_REQUEST'
  | 'BOOTSTRAP_FAILED'
  | 'CAPABILITY_DENIED'
  | 'DOCUMENT_NOT_OPEN'
  | 'EDITOR_FAILED'
  | 'IPC_SENDER_REJECTED'
  | 'OPEN_FAILED'
  | 'PLUGIN_FAILED'
  | 'PLUGIN_UNKNOWN'
  | 'PLUGIN_STALE'
  | 'PLUGIN_NOT_HYDRATED'
  | 'PLUGIN_CLEANUP_FAILED'
  | 'PLUGIN_GENERATION_FAILED'
  | 'PLUGIN_RENDERER_DISPOSED'
  | 'SAVE_FAILED'
  | 'SEMANTIC_MISMATCH'
  | 'SERVICE_FAILED'
  | 'SERVICE_CANCELLED'
  | 'SERVICE_STOPPED'
  | 'SOURCE_MAP_UNSUPPORTED'
  | 'STRUCTURE_CHANGED'
  | 'TEST_MODE_REQUIRED'
  | 'TIMEOUT';

export interface NotoError {
  code: NotoErrorCode;
  message: string;
}

export const NOTO_ERROR_CODES = [
  'BAD_REQUEST',
  'BOOTSTRAP_FAILED',
  'CAPABILITY_DENIED',
  'DOCUMENT_NOT_OPEN',
  'EDITOR_FAILED',
  'IPC_SENDER_REJECTED',
  'OPEN_FAILED',
  'PLUGIN_FAILED',
  'PLUGIN_UNKNOWN',
  'PLUGIN_STALE',
  'PLUGIN_NOT_HYDRATED',
  'PLUGIN_CLEANUP_FAILED',
  'PLUGIN_GENERATION_FAILED',
  'PLUGIN_RENDERER_DISPOSED',
  'SAVE_FAILED',
  'SEMANTIC_MISMATCH',
  'SERVICE_FAILED',
  'SERVICE_CANCELLED',
  'SERVICE_STOPPED',
  'SOURCE_MAP_UNSUPPORTED',
  'STRUCTURE_CHANGED',
  'TEST_MODE_REQUIRED',
  'TIMEOUT',
] as const satisfies readonly NotoErrorCode[];
