version: '3.8'
services:
  qwen3-embedding:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0  # ,1,2,3  # 根据实际GPU数量调整
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
